#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	passenger_status
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup ruby env"
mkdir -p /home/ruby/www/shared
chown -R ruby:ruby /home/ruby/www

gem install gemenv -v 0.0.3

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
